### ISSUE TITLE
[Bug/iCloud] iCloud login doesn't function, "An unknown error occurred."

### ISSUE THREAD

**Issue by LunarN0v4** [dockur/macos#107]
### Operating system

Debian GNU/Linux 12 (bookworm)

### Description

iCloud login fails with "An unknown error occurred.", no actual description of the problem. I have tried every prompt in the system and they all fail with iCloud login.

### Docker compose

```yaml
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15"
      DISK_SIZE: "256G"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
    volumes:
      - ./storage:/storage
```

### Docker log

❯ Starting macOS for Docker v1.14...
❯ For support visit https://github.com/dockur/macos
❯ CPU: Intel Xeon CPU E5 2630 v3 | RAM: 54/63 GB | DISK: 6314 GB (ext4) | HOST: 6.1.0-26-amd64...

^[[1;34m❯ ^[[1;36mDownloading macOS 15 recovery image...^[[0m
Downloading 062-24352...
Saving http://oscdn.apple.com/content/downloads/58/14/062-24352/huowb7csccndr18cneqn3epe6quo5yt061/RecoveryImage/BaseSystem.chunklist to /storage/tmp/BaseSystem.chunklist...
^M100.0% downloaded
Download complete!
Saving http://oscdn.apple.com/content/downloads/58/14/062-24352/huowb7csccndr18cneqn3epe6quo5yt061/RecoveryImage/BaseSystem.dmg to /storage/tmp/BaseSystem.dmg...
^M1.1% downloaded^M2.2% downloaded^M3.3% downloaded^M4.5% downloaded^M5.6% downloaded^M6.7% downloaded^M7.8% downloaded^M8.9% downloaded^M10.0% downloaded^M11.1% downloaded^M12.3% downloaded^M13.4% downloaded^M14.5% downloaded^M15.6% do>
Download complete!
Verifying image with chunklist...
^MChunk 10 (10485760 bytes)^MChunk 20 (10485760 bytes)^MChunk 30 (10485760 bytes)^MChunk 40 (10485760 bytes)^MChunk 50 (10485760 bytes)^MChunk 60 (10485760 bytes)^MChunk 70 (10485760 bytes)^MChunk 80 (10485760 bytes)
Image verification complete!
^[[1;34m❯ ^[[1;36mCreating a 256G growable disk image in raw format...^[[0m
^[[1;34m❯ ^[[1;36mExtracting boot image...^[[0m
^[[1;34m❯ ^[[1;36mBooting macOS 1920x1080 using QEMU v9.1.0...^[[0m
^[[2J^[[01;01H^[[=3h^[[2J^[[01;01H^[[2J^[[01;01H^[[=3h^[[2J^[[01;01H^[[2J^[[01;01H^[[=3h^[[2J^[[01;01HBdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/67a839a9-e202-49e0-ae85-e1cb32bcbc41)
