### ISSUE TITLE
[Question]:  Why does installation take so long? 

### ISSUE THREAD

**Issue by EnochGao** [dockur/macos#129]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/macos/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Is this normal？
![image](https://github.com/user-attachments/assets/2ac8be18-5613-4795-9031-14ca3c11355a)

**Comment by EnochGao** [comment]
my compose.yml:
```yml
name: macos
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    volumes:
      - /var/osx:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
```
