### ISSUE TITLE
Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory

### ISSUE THREAD

**Issue by ilbebino08** [dockur/macos#144]
### Operating system

Windows 11

### Description

running the command: `docker compose up` returns the following error: 
`Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory`

### Docker compose

```
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
```

### Docker log

 ✔ Network osx_default  Created                                                                                    0.0s
 ✔ Container macos      Created                                                                                    0.1s
Attaching to macos
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory
