### ISSUE TITLE
No internet connection with default install on Synology NAS (eth0 inactive)

### ISSUE THREAD

**Issue by tempelmann** [dockur/macos#250]
### Operating system

Synology (AMD Ryzen R1600), DSM 7.2.2

### Description

This may be the same issue as #173, but since that one ran thru some other solution attempts, I'm opening a new ticket in case they're actually different issues.

Basically, after successfully starting up the container for macOS 12 using the recommended yaml, the Recovery System is not able to connect to the internet. Checking with the macOS Terminal, "ifconfig" shows that the eh0 interface has a 169... IP.

I then tried the various options given on https://hub.docker.com/r/dockurr/macos to assign a vlan, with no success.

One suspicion I had: The synology has multiuple eth interfaces, but the first 2 are offline. If docker creates the bridge always for the eth0, then this can't work. Sadly, I was not able to verify this, because the Container Manager for the Syno DSM does not show the assigned interface for the bridge, nor can I assign one when creating the bridge. So I tried to the "docker network create" cmd where I can assign the bridge, but that led to "the device is busy" errors. So I gave up on this. I also ran into an error when trying the DHCP option. In the end, I had ended up with the config below, which basically is the default but with the "/dev/vhost-net" dev and the "device_cgroup_rules" added. Suddenly, the macOS has a working internet connection, although, oddly, "ifconfig" in the Rescue System showed the IP "20.20.20.21". Regardless, I'm now able to install macOS Monterey.

I'll report more once the install is finished, but I wanted to get this out while waiting. Perhaps you can make sense of this. It would also be nice if someone with a better understanding can test this setup on a Synology NAS to make sure it always works, including creating a vlan (which I couldn't get working either) and using DHCP.

### Docker compose

```
# Refs:
# https://www.heise.de/ratgeber/macOS-im-Docker-Container-So-klappt-es-mit-dem-virtuellen-Mac-10327198.html?seite=all
# https://hub.docker.com/r/dockurr/macos
#
services:
  macos:
    image: dockurr/macos
    container_name: macos12
    environment:
      VERSION: "12"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "128G"
      WIDTH: "1440"
      HEIGHT: "960"
#      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net # added
    device_cgroup_rules:
      - 'c *:* rwm' #added
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos12:/storage
    restart: always
    stop_grace_period: 2m
#    networks:
#      vlan6:
#        ipv4_address: 192.168.6.100
#networks:
#  vlan6:
#    external: true
```

### Docker log

Sorry, can't get any logs - both the UI and the command hang, displaying nothing.
