### ISSUE TITLE
How to use full Screen Sharing?

### ISSUE THREAD

**Issue by tempelmann** [dockur/macos#252]
### Operating system

Syno DSM

### Description

Using the plain VNC protocol to access the macOS VM is quite painful when you're trying to control the VM from a Mac.
Ideally, the Mac's Screen Sharing app should be used for the best user experience.
However, even when I open all the related ports, it Screen Sharing cannot connect:

```
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
      - 5901:5901/udp
      - 5902:5902/udp
      - 3283:3283/tcp
      - 3283:3283/udp
      - 88:88
```

I believe that's because qemu inserts its own vnc server. So I need to disable that "feature". Googling the problem I found that qemu has a cmdline option for that: "--disable-vnc". But since we're using docker compose here, I cannot figure out how to apply this option.

So, how what must I change to have the docker container run qemu without activating its vnc-server?

And may I then also suggest to add this "trick" to the readme?

## Update

I also tried adding the two environment vars suggested in https://github.com/dockur/macos/issues/131#issuecomment-2480851179 but that, while it seems to disable the qemu vnc service, still won't let me login via Screen Sharing (while I can still ssh into the VM). Now the connection attempt times out, though I can see that port 5900 is listening on the Mac.

Here's the config I'm currently using (the "NETWORK: user" settings seems to be needed, or I can't even ssh into the Mac):

```
services:
  macos:
    image: dockurr/macos
    container_name: macos12
    environment:
      VERSION: "12"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "128G"
      WIDTH: "1440"
      HEIGHT: "960"
      NETWORK: "user"
      USER_PORTS: "5900"
      DISPLAY: "disabled"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
      - 5901:5901/udp
      - 5902:5902/udp
      - 8022:22
    volumes:
      - ./macos12:/storage
    restart: "no"  # on-failure:2
    stop_grace_period: 2m
```
