### ISSUE TITLE
Increasing Disk Space is not taken in count

### ISSUE THREAD

**Issue by RambokDev** [dockur/macos#255]
### Operating system

Ubuntu 24.04.2

### Description

Increasing disk space is not taken into account. Any idea on this ? 

The container explicitly says that it has been resized.

![Image](https://github.com/user-attachments/assets/9e947a35-15fa-4202-b7d9-5ba18853504b)

A bug occurred on the Docker machine.

![Image](https://github.com/user-attachments/assets/939616e0-b59f-46f7-b45e-08e769341ec4)

Do I have to mount or resize the disk myself?

### Docker compose

```yaml
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      RAM_SIZE: "32G"
      CPU_CORES: "8"
      DISK_SIZE: "256G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
      - 8022:22/tcp
    volumes:
      - ./macos_sonoma:/storage
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
macos  | ❯ Starting macOS for Docker v2.13...
macos  | ❯ For support visit https://github.com/dockur/macos
macos  | ❯ CPU: AMD Ryzen 7 7840HS w Radeon 780M Graphics | RAM: 52/62 GB | DISK: 120 GB (ext4) | KERNEL: 6.8.0-58...
macos  | 
macos  | ❯ Building boot image...
macos  | ❯ 
macos  | ❯ Model: iMacPro1,1
macos  | ❯ Rom: 0016cb9df061
macos  | ❯ Serial: C02VC4Z1HX87
macos  | ❯ Board: C02736270GUJG36JC
macos  | ❯ 
macos  | ❯ Booting macOS using QEMU v9.2.92...
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
macos  | BdsDxe: failed to load Boot0080 "Mac OS X" from PciRoot(0x0)/Pci(0xA,0x0)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,F9A5A03AEFB7FA45B1F76D6DC9E4DDB2)/\6C9A32F3-ED8F-44B4-94E0-8CB1A57B3087\System\Library\CoreServices\boot.efi: Not Found
macos  | BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
macos  | BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos  | BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos  | #[EB|LOG:EXITBS:END] _
macos  | #[EB.BST.FBS|-]
macos  | #[EB|B:BOOT]
macos  | #[EB|LOG:HANDOFF TO XNU] _
macos  | ======== End of efiboot serial output. ========
```
