### ISSUE TITLE
Nested KVM virtualization

### ISSUE THREAD

**Issue by Soluce-Technologies** [dockur/macos#259]
### Operating system

Ubuntu 24.04

### Description

I have this warning : 

 Warning: Nested KVM virtualization detected, this might cause issues running macOS!

The service start when, but then during the installation process after 1 min machine crash, mac os restart. I am unable to complete the installation. 

Any idea ? 

### Docker compose

```yaml
name: macos-1

services:
  macos:
    image: dockurr/macos
    container_name: sonoma
    environment:
      VERSION: "14"
      RAM_SIZE: "32G"
      DISK_SIZE: "256G"
      CPU_CORES: "8"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "5900:5900/tcp"
      - "5900:5900/udp"
      - "8022:22/tcp"


    volumes:
      - ./macos_sonoma:/storage
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
cezigue_sonoma  | ❯ Starting macOS for Docker v2.14...
cezigue_sonoma  | ❯ For support visit https://github.com/dockur/macos
cezigue_sonoma  | ❯ CPU: AMD EPYC Milan | RAM: 61/62 GB | DISK: 376 GB (ext4) | KERNEL: 6.8.0-56...
cezigue_sonoma  | 
cezigue_sonoma  | ❯ Building boot image...
cezigue_sonoma  | ❯ 
cezigue_sonoma  | ❯ Model: iMacPro1,1
cezigue_sonoma  | ❯ Rom: 0016cb19838d
cezigue_sonoma  | ❯ Serial: C02FCPYQHX87
cezigue_sonoma  | ❯ Board: C02109102J9JG36AD
cezigue_sonoma  | ❯ 
cezigue_sonoma  | ❯ Warning: Nested KVM virtualization detected, this might cause issues running macOS!
cezigue_sonoma  | ❯ Booting macOS using QEMU v10.0.0...
cezigue_sonoma  | 
=
=
=
BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
cezigue_sonoma  | BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
cezigue_sonoma  | BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
cezigue_sonoma  | #[EB|LOG:EXITBS:END] _
cezigue_sonoma  | #[EB.BST.FBS|-]
cezigue_sonoma  | #[EB|B:BOOT]
cezigue_sonoma  | #[EB|LOG:HANDOFF TO XNU] _
cezigue_sonoma  | ======== End of efiboot serial output. ========
cezigue_sonoma  |
```
