### ISSUE TITLE
macOS fails to boot

### ISSUE THREAD

**Issue by zymsbgt** [dockur/macos#67]
### Operating system

VanillaOS 2 (Orchid)

### Description

I am trying to run this image through Podman on my system, using podman-compose. When I try to run it, it crashes instantly. This same error occurs on both macOS Ventura and Monterey

### Docker compose

services:
  macos:
    image: ghcr.io/dockur/macos
    container_name: macos
    environment:
      VERSION: "monterey"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m

### Docker log

BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========
qemu-system-x86_64: terminating on signal 2 from pid 1 (/usr/bin/tini)

**Comment by dajix350** [comment]
I got this same error on Arch using docker-compose on both Ventura and Monterey.

**Comment by cristianpenteado** [comment]
I got the same error running on Fedora 40

**Comment by drkx** [comment]
What kind of partition did you create? I'm not sure if it has something to do with it, but when I selected case sensitive with partitioning my installation didn't work. Since I also changed the OS version from Sonoma to Montery I'm not sure if this was the issue though.

**Comment by GitHanter** [comment]
Same issue 
```yaml
services:
  osx:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "sequoia"
      DISK_SIZE: "64G"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m

```
Failed to boot
```shell
BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
macos  | BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos  | BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos  | #[EB|LOG:EXITBS:END] _
macos  | #[EB.BST.FBS|-]
macos  | #[EB|B:BOOT]
macos  | #[EB|LOG:HANDOFF TO XNU] _
macos  | ======== End of efiboot serial output. ========

```

neofetch of my ubuntu 24.10 system

```shell
OS: Ubuntu 24.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 80YX Lenovo Y920-17IKB 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.11.0-8-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 11 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3594 (dpkg), 138 (brew), 158 (flatpak), 46 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.9 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 47.0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Mojave-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: WhiteSur [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: terminator 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-7820HK (8) @ 3.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 1070 Mobile 
      -+sssssssssssssssssyyyssss+-         Memory: 20691MiB / 61937MiB 

```

**Comment by QYG2297248353** [comment]
compose.yml
```yml
networks:
    1panel-network:
        external: true
services:
    macos:
        cap_add:
            - NET_ADMIN
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        devices:
            - /dev/kvm:/dev/kvm
            - /dev/dri:/dev/dri
        env_file:
            - /etc/1panel/envs/global.env
            - ${ENV_FILE:-/etc/1panel/envs/default.env}
        environment:
            - VERSION=${VERSION}
        image: dockurr/macos:1.14
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8006
            - ${HOST_IP}:${PANEL_APP_PORT_REMOTE}:5900/tcp
            - ${HOST_IP}:${PANEL_APP_PORT_REMOTE}:5900/udp
        restart: always
        stop_grace_period: 2m
        volumes:
            - ${MACOS_STORAGE_ROOT_PATH}/storage:/storage
```
env
```
CONTAINER_NAME="macos-ms"
CPUS=0
CPU_CORES=4
DISK_SIZE="64G"
HOST_IP=""
MACOS_STORAGE_ROOT_PATH="/home/data/macos"
MEMORY_LIMIT=0
PANEL_APP_PORT_HTTP=8122
PANEL_APP_PORT_REMOTE=5900
RAM_SIZE="8G"
VERSION=15
ENV_FILE=/opt/1panel/apps/local/macos/macos/.env
```

日志
```
macos-ms  | ======== End of efiboot serial output. ========
macos-ms  | [2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01HBdsDxe: failed to load Boot0080 "Mac OS X" from PciRoot(0x0)/Pci(0xA,0x0)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,471F93308231524A95328E3E6A1889E8)/\9F4330E7-AE1E-4144-8069-E5A69EECA87C\System\Library\CoreServices\boot.efi: Not Found
macos-ms  | BdsDxe: failed to load Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0xA,0x0): Not Found
macos-ms  | BdsDxe: loading Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos-ms  | BdsDxe: starting Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x5,0x0)
macos-ms  | #[EB|LOG:EXITBS:END] _
macos-ms  | #[EB.BST.FBS|-]
macos-ms  | #[EB|B:BOOT]
macos-ms  | #[EB|LOG:HANDOFF TO XNU] _
```
