### ISSUE TITLE
[Bug]: OSError: [Errno 25] Inappropriate ioctl for device ( ERROR: Failed to fetch macOS recovery image with board id)

### ISSUE THREAD

**Issue by jbramburek** [dockur/macos#83]
### Operating system

Ubuntu 24.04

### Description

Using the latest (1.11) image I am getting the error
```
macos  | OSError: [Errno 25] Inappropriate ioctl for device
macos  | ❯ ERROR: Failed to fetch macOS "Sonoma" recovery image with board id "Mac-827FAC58A8FDFA22"!
```

Tried sequoia and sonoma, happens for both.

The image 1.10 does not produce the error.

(I checked a similar issue https://github.com/dockur/macos/issues/82 but it looks different to me)

### Docker compose

```
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "sonoma"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      DISK_SIZE: "256G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
    volumes:
      - /storage/osx:/storage
 ```

### Docker log

```
cos  | ❯ Starting macOS for Docker v1.11...
macos  | ❯ For support visit https://github.com/dockur/macos
macos  | ❯ CPU: AMD Ryzen 5 4600G | RAM: 7/8 GB | DISK: 478 GB (ext4) | HOST: 6.8.0-45...
macos  |
macos  | ❯ Downloading macOS Sonoma recovery image...
macos  | Downloading 696-08090...
macos  | Saving http://oscdn.apple.com/content/downloads/11/58/062-53943/of12aseueo2jnehp03qh5g3o17lx4139t1/RecoveryImage/BaseSystem.chunklist to /storage/tmp/BaseSystem.chunklist...
macos  | Traceback (most recent call last):
macos  |   File "/run/macrecovery.py", line 514, in <module>
macos  |     sys.exit(main())
macos  |              ^^^^^^
macos  |   File "/run/macrecovery.py", line 502, in main
macos  |     return action_download(args)
macos  |            ^^^^^^^^^^^^^^^^^^^^^
macos  |   File "/run/macrecovery.py", line 298, in action_download
macos  |     cnkpath = save_image(info[INFO_SIGN_LINK], info[INFO_SIGN_SESS], cnkname, args.outdir)
macos  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
macos  |   File "/run/macrecovery.py", line 226, in save_image
macos  |     terminalsize = os.get_terminal_size().columns
macos  |                    ^^^^^^^^^^^^^^^^^^^^^^
macos  | OSError: [Errno 25] Inappropriate ioctl for device
macos  | ❯ ERROR: Failed to fetch macOS "Sonoma" recovery image with board id "Mac-827FAC58A8FDFA22"!
```
