### ISSUE TITLE
Sign in error "The maximum number of free accounts have been activated on this mac"

### ISSUE THREAD

**Issue by ToanTNM** [dockur/macos#98]
### Operating system

Ubuntu 22.04 WSL

### Description

After install Big Sur, i sign-in with my account and it throw error: "MOBILEME_CREATE_UNAVAILABLE_MAC"

I upgrade to newest version and sign-in again, and it throw: "The maximum number of free accounts have been activated on this mac".

Maybe it the same issuse here https://github.com/sickcodes/Docker-OSX/issues/727

How can I fix it.

### Docker compose

```yml
services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "big-sur"
      DISK_SIZE: "256G"
      CPU_CORES: "4"
      ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    devices:
      - /dev/kvm
      - /dev/bus/usb
    volumes:
      - /var/osx:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
```

### Docker log

No log
